# Generated by Django 4.0.2 on 2022-02-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_firstlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstlogin',
            name='first_login',
            field=models.BooleanField(default=False),
        ),
    ]
